export const studentsData = [
  {
    id: 1,
    name: "John",
    surname: "Doe",
    college: "ABC University",
    course: "Computer Science",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    name: "Jane",
    surname: "Smith",
    college: "XYZ College",
    course: "Engineering",
    email: "jane.smith@example.com",
  },
  {
    id: 3,
    name: "Alice",
    surname: "Johnson",
    college: "DEF University",
    course: "Medicine",
    email: "alice.johnson@example.com",
  },
  {
    id: 4,
    name: "Michael",
    surname: "Brown",
    college: "GHI College",
    course: "Business Administration",
    email: "michael.brown@example.com",
  },
  {
    id: 5,
    name: "Emma",
    surname: "Garcia",
    college: "LMN University",
    course: "Psychology",
    email: "emma.garcia@example.com",
  },
  {
    id: 6,
    name: "Daniel",
    surname: "Martinez",
    college: "PQR College",
    course: "Economics",
    email: "daniel.martinez@example.com",
  },
  {
    id: 7,
    name: "Sophia",
    surname: "Anderson",
    college: "STU University",
    course: "Biology",
    email: "sophia.anderson@example.com",
  },
  {
    id: 8,
    name: "Liam",
    surname: "Wilson",
    college: "VWX College",
    course: "Mathematics",
    email: "liam.wilson@example.com",
  },
];

export const professorsData = [];
